### ISSUE TITLE
"Exception in thread AsyncoreThread" when exiting

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Bitmessage/PyBitmessage#1008]
This exception occurred when exiting BM (A)

BM was running for about 40 mins
* I am trying to run it via tor (BM gets yellow signal, but no real, working connection)

Below, the KeyError value was replaced (a.b.c.d), but it is my local IP.
I noticed that in this session BM tried to connect 4x to:
* a.b.c.d:8444

Each time like 5-7x directly after another

Exception in thread AsyncoreThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/AngelaMerkel/bitmessage/PyBitmessage-0.6/src/network/networkthread.py", line 20, in run
    BMConnectionPool().loop()
  File "/home/AngelaMerkel/bitmessage/PyBitmessage-0.6/src/network/connectionpool.py", line 204, in loop
    self.removeConnection(i)
  File "/home/AngelaMerkel/bitmessage/PyBitmessage-0.6/src/network/connectionpool.py", line 71, in removeConnection
    del self.udpSockets[connection.destination.host]
KeyError: 'a.b.c.d'

on request more info can be provided

(A) BM version 0.6.2, [branch 0.6](https://github.com/Bitmessage/PyBitmessage/tree/v0.6), last commit: 6044df5

**Comment by PeterSurda** [comment]
I believe you, I'll fix it together with the other asyncore-related bugs.

**Comment by PeterSurda** [comment]
Let me know if you're still having this problem after the fix.

**Comment by Erkan-Yilmaz** [comment]
tried 2x, but didn't happen...
I'll try l8 more
