### ISSUE TITLE
AttributeError: 'Peer' object has no attribute 'handle_close'

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Bitmessage/PyBitmessage#1013]
I think this happens when I activate or deactivate something in the network settings (tor or incr./decr. connections)

* when I have more time, I have to investigate more, reporting now so I don't forget

dev 0.6 branch with commit: a3a55e5

Exception in thread AsyncoreThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/ex_NSA_chief_Alexander/PyBitmessage-0.6.2__dev__from_2017_06_11__commit_a3a55e5/src/network/networkthread.py", line 20, in run
    BMConnectionPool().loop()
  File "/ex_NSA_chief_Alexander/PyBitmessage-0.6.2__dev__from_2017_06_11__commit_a3a55e5/src/network/connectionpool.py", line 179, in loop
    i.handle_close()
AttributeError: 'Peer' object has no attribute 'handle_close'

**Comment by PeterSurda** [comment]
This should be fixed in the meantime.
