### ISSUE TITLE
Fast PoW got exception

### ISSUE THREAD

**Issue by darket-software** [Bitmessage/PyBitmessage#1086]
When I attempt to send a message and it enters the doingmsgpow state, it never completes and I see the following error in /home/user/.config/PyBitmessage/debug.log:

```
ERROR - Fast PoW got exception:
Traceback (most recent call last):
  File "/opt/bitmessage/src/proofofwork.py", line 222, in run
    return _doFastPoW(target, initialHash)
  File "/opt/bitmessage/src/proofofwork.py", line 72, in _doFastPoW
    pool = Pool(processes=pool_size)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 129, in __init__
    os._exit(code)
  File "/opt/bitmessage/src/helper_generic.py", line 53, in signal_handler
    raise SystemExit
SystemExit
```

This node previously sent a few messages fine, but I did kill -9 it once. Could this have broken something?

UPDATE: I just tried again and it sent a few messages, then this error randomly occurred again. How can I narrow down the cause of this?

**Comment by PeterSurda** [comment]
Use the C PoW.

**Comment by darket-software** [comment]
@PeterSurda Sorry, I'm not sure how to change to the C PoW. Sorry if I'm just overlooking it somewhere in the docs. Any hints?

**Comment by PeterSurda** [comment]
https://bitmessage.org/wiki/Compiling_instructions

**Comment by darket-software** [comment]
Thanks.
