### ISSUE TITLE
report after install

### ISSUE THREAD

**Issue by rossy1991** [Bitmessage/PyBitmessage#1133]
Hallo, here is what I see in terminal after lunch PyBitmessage in Ubuntu...red control lights and no connection with others. here are just some bytes...I can only send messages from myself to myself :-) thats not why I have installed it :-)...Im lama so please slowly

mj@mj-3000-N200:~/PyBitmessage-0.6.3.2/src$ ./bitmessagemain.py
ERROR: The msgpack package is not available.It is highly recommended for messages coding.
ERROR: On Ubuntu, try running "apt-get install python-msgpack" as root.
Loading existing config files from /home/mj/.config/PyBitmessage/
Using default logger configuration
make: Entering directory `/home/mj/PyBitmessage-0.6.3.2/src/bitmsghash'
g++ -Wall -O3 -march=native -fPIC  -c bitmsghash.cpp
make: g++: Command not found
make: *** [bitmsghash.o] Error 127
make: Leaving directory `/home/mj/PyBitmessage-0.6.3.2/src/bitmsghash'
2018-02-14 22:12:25,724 - ERROR - /home/mj/.namecoin/namecoin.conf unreadable or missing, Namecoin support deactivated
2018-02-14 22:12:26,849 - WARNING - No indicator plugin found
2018-02-14 22:12:26,850 - WARNING - No notification.message plugin found
2018-02-14 22:12:31,852 - WARNING - No notification.sound plugin found
2018-02-14 22:12:46,290 - ERROR - SOCKS DNS resolving failed
Traceback (most recent call last):
  File "/home/mj/PyBitmessage-0.6.3.2/src/helper_bootstrap.py", line 99, in dns
    ip = sock.resolve("bootstrap" + str(port) + ".bitmessage.org")
  File "/home/mj/PyBitmessage-0.6.3.2/src/socks/__init__.py", line 460, in resolve
    return self.__resolvesocks5(host)
  File "/home/mj/PyBitmessage-0.6.3.2/src/socks/__init__.py", line 267, in __resolvesocks5
    resp = self.__recvall(4)
  File "/home/mj/PyBitmessage-0.6.3.2/src/socks/__init__.py", line 139, in __recvall
    raise GeneralProxyError((6, "timed out"))
GeneralProxyError: (6, 'timed out')
2018-02-14 22:13:06,306 - ERROR - SOCKS DNS resolving failed
Traceback (most recent call last):
  File "/home/mj/PyBitmessage-0.6.3.2/src/helper_bootstrap.py", line 99, in dns
    ip = sock.resolve("bootstrap" + str(port) + ".bitmessage.org")
  File "/home/mj/PyBitmessage-0.6.3.2/src/socks/__init__.py", line 460, in resolve
    return self.__resolvesocks5(host)
  File "/home/mj/PyBitmessage-0.6.3.2/src/socks/__init__.py", line 267, in __resolvesocks5
    resp = self.__recvall(4)
  File "/home/mj/PyBitmessage-0.6.3.2/src/socks/__init__.py", line 139, in __recvall
    raise GeneralProxyError((6, "timed out"))
GeneralProxyError: (6, 'timed out')
Exception in thread ReceiveQueue_0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/receivequeuethread.py", line 43, in run
    BMConnectionPool().getConnectionByAddr(dest).process()
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/advanceddispatcher.py", line 61, in process
    if not getattr(self, "state_" + str(self.state))():
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/socks5.py", line 42, in state_auth_1
    ret = struct.unpack('BB', self.read_buf)
error: unpack requires a string argument of length 2

Exception in thread ReceiveQueue_1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/receivequeuethread.py", line 43, in run
    BMConnectionPool().getConnectionByAddr(dest).process()
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/advanceddispatcher.py", line 61, in process
    if not getattr(self, "state_" + str(self.state))():
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/socks5.py", line 42, in state_auth_1
    ret = struct.unpack('BB', self.read_buf)
error: unpack requires a string argument of length 2

Exception in thread ReceiveQueue_2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/receivequeuethread.py", line 43, in run
    BMConnectionPool().getConnectionByAddr(dest).process()
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/advanceddispatcher.py", line 61, in process
    if not getattr(self, "state_" + str(self.state))():
  File "/home/mj/PyBitmessage-0.6.3.2/src/network/socks5.py", line 42, in state_auth_1
    ret = struct.unpack('BB', self.read_buf)
error: unpack requires a string argument of length 2

I also tried bitmessage.me, but there is no response at all...
thanks for help

**Comment by PeterSurda** [comment]
Kindly consult the https://bitmessage.org/wiki/Compiling_instructions, there is a dependency checking script and a build/installation script. You don't need them but if you're having problems it's the safest way.
