### ISSUE TITLE
Crashing on Boot

### ISSUE THREAD

**Issue by maraymer** [Bitmessage/PyBitmessage#1333]
$ python src/bitmessagemain.py 
Loading existing config files from /home/.config/PyBitmessage/
2018-08-05 13:19:02,170 - WARNING - Using default logger configuration
2018-08-05 13:19:02,592 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "src/bitmessagemain.py", line 507, in <module>
  File "src/bitmessagemain.py", line 503, in main
  File "src/bitmessagemain.py", line 276, in start
  File "PyBitmessage/src/knownnodes.py", line 100, in readKnownNodes
    pickle_deserialize_old_knownnodes(source)
  File "PyBitmessage/src/knownnodes.py", line 63, in pickle_deserialize_old_knownnodes
    knownNodes = pickle.load(source)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 886, in load_eof
    raise EOFError
EOFError
Cleaning up lockfile

**Comment by PeterSurda** [comment]
Try deleting `knownnodes.dat` or the current code from v0.6 branch.

**Comment by maraymer** [comment]
Thanks just to catch up that I did that before you replied and it worked.  :-)  Thanks @PeterSurda
