### ISSUE TITLE
bitmessage --curses  crashes over UTF / Unicode

### ISSUE THREAD

**Issue by dimyme** [Bitmessage/PyBitmessage#1345]
the curses mode could use a lil fixing ...  then it works great

2018-09-18  15:29:45,416 - CRITICAL - Unhandled exception

Traceback (most recent call last):

  File "bitmessagemain.py", line 507, in <module>

    main()

  File "bitmessagemain.py", line 503, in main    mainprogram.start()

  File "bitmessagemain.py", line 398, in start    bitmessagecurses.runwrapper()

  File "/z/src/bitmessagecurses/__init__.py", line 1004, in runwrapper    curses.wrapper(run)

  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper    return func(stdscr, *args, **kwds)

  File "/z/src/bitmessagecurses/__init__.py", line 1049, in run    handlech(stdscr.getch(), stdscr)

  File "/z/src/bitmessagecurses/__init__.py", line 334, in handlech    sendMessage(fromaddr, toaddr, ischan, subject, body, True)

  File "/z/src/bitmessagecurses/__init__.py", line 735, in sendMessage     r, t = d.inputbox("Message body", 10, 80, init=body)

  File "/usr/lib/python2.7/site-packages/dialog.py", line 2788, in inputbox     kwargs, strip_xdialog_newline=True, raw_help=True)

  File "/usr/lib/python2.7/site-packages/dialog.py", line 1748, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)

  File "/usr/lib/python2.7/site-packages/dialog.py", line 1540, in _perform
    **kwargs)

  File "/usr/lib/python2.7/site-packages/dialog.py", line 1301, in _call_program
    cmdargs = self.dash_escape_nf(cmdargs)

  File "/usr/lib/python2.7/site-packages/dialog.py", line 1095, in dash_escape_nf
    return _dash_escape_nf(args)

  File "/usr/lib/python2.7/site-packages/dialog.py", line 323, in _dash_escape_nf
    l = _dash_escape(args[1:])

  File "/usr/lib/python2.7/site-packages/dialog.py", line 306, in _dash_escape
    if arg.startswith("--"):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 134: ordinal not in range(128)`

**Comment by dimyme** [comment]
I latest   curses   __init__.py   is mostly fixed .  very useable now !

**Comment by dimyme** [comment]
but send BM does not yet work, but easy to fix I guess
