### ISSUE TITLE
segmentation fault at launch - ICE default IO error handler doing an exit()

### ISSUE THREAD

**Issue by tuxayo** [Bitmessage/PyBitmessage#1375]
Launch where there was an error.
```
2018-10-17 09:16:51,536 - ERROR - Failed to set locale to eo_XX.UTF-8
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 103, in change_translation
    l10n.setlocale(locale.LC_ALL, lang)
  File "/usr/share/pybitmessage/l10n.py", line 83, in setlocale
    locale.setlocale(category, newlocale)
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
2018-10-17 09:16:51,590 - ERROR - Failed to set locale to eo_XX.UTF-8
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 103, in change_translation
    l10n.setlocale(locale.LC_ALL, lang)
  File "/usr/share/pybitmessage/l10n.py", line 83, in setlocale
    locale.setlocale(category, newlocale)
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
2018-10-17 09:16:51,591 - ERROR - Failed to set locale to eo_XX.ISO8859-3
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 103, in change_translation
    l10n.setlocale(locale.LC_ALL, lang)
  File "/usr/share/pybitmessage/l10n.py", line 83, in setlocale
    locale.setlocale(category, newlocale)
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
2018-10-17 09:16:55,805 - WARNING - No indicator plugin found
2018-10-17 09:16:55,870 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/networkstatus.py", line 157, in updateNetworkStatusTab
    self.window().setStatusIcon('yellow')
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 1623, in setStatusIcon
    sound.SOUND_CONNECTED)
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 1379, in notifierShow
    self.playSound(category, label)
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 1324, in playSound
    return self._theme_player(category, label)
AttributeError: 'MyForm' object has no attribute '_theme_player'
ICE default IO error handler doing an exit(), pid = 1772, errno = 32

[6]    1772 segmentation fault (core dumped)  pybitmessage

```
Successful launch just after:
```
2018-10-17 09:36:16,926 - ERROR - Failed to set locale to eo_XX.UTF-8
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 103, in change_translation
    l10n.setlocale(locale.LC_ALL, lang)
  File "/usr/share/pybitmessage/l10n.py", line 83, in setlocale
    locale.setlocale(category, newlocale)
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
2018-10-17 09:36:16,930 - ERROR - Failed to set locale to eo_XX.UTF-8
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 103, in change_translation
    l10n.setlocale(locale.LC_ALL, lang)
  File "/usr/share/pybitmessage/l10n.py", line 83, in setlocale
    locale.setlocale(category, newlocale)
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
2018-10-17 09:36:16,931 - ERROR - Failed to set locale to eo_XX.ISO8859-3
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 103, in change_translation
    l10n.setlocale(locale.LC_ALL, lang)
  File "/usr/share/pybitmessage/l10n.py", line 83, in setlocale
    locale.setlocale(category, newlocale)
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
2018-10-17 09:36:17,201 - WARNING - No indicator plugin found
2018-10-17 09:36:44,271 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "/usr/share/pybitmessage/bitmessageqt/networkstatus.py", line 157, in updateNetworkStatusTab
    self.window().setStatusIcon('yellow')
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 1623, in setStatusIcon
    sound.SOUND_CONNECTED)
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 1379, in notifierShow
    self.playSound(category, label)
  File "/usr/share/pybitmessage/bitmessageqt/__init__.py", line 1324, in playSound
    return self._theme_player(category, label)
AttributeError: 'MyForm' object has no attribute '_theme_player'

```

So, only the end of the error log is relevant.

Context: launching everything at once after boot on my computer (browser, mail client, torrent client, JOSM (heavy app to edit OpenStreetMap)) so the PC was working hard during at least 1.5 minutes to open everything.

So that might be some race condition that is more likely to happen due to the slow launch in scare CPU & I/O condition.

Maybe some other app was messing with ICE at the same time?
https://stackoverflow.com/questions/20621070/ice-default-io-error-handler-doing-an-exit-pid-11281-errno-4/22038069#22038069

Anyway, we will see if that happens again.

**Comment by g1itch** [comment]
I have no idea about ICE, but I see that you probably have no `sounds` directory in BM's appdata (usually `~/.config/PyBitmessage`) and I should probably add `AttributeError` to [this except statement](../blob/v0.6/src/bitmessageqt/__init__.py#L1333) for this case.

**Comment by g1itch** [comment]
Also it seems you use an outdated source. Please try with latest v0.6.

**Comment by g1itch** [comment]
So did you try the latest source? Are you still experiencing the problem? Otherwise I'm going to close this issue.
