### ISSUE TITLE
ValueError: API 'QDate' has already been set to version 1`

### ISSUE THREAD

**Issue by bl4k1st** [Bitmessage/PyBitmessage#1418]
I constantly get the following error:

`Loading existing config files from /root/.config/PyBitmessage/
Using default logger configuration
2018-10-09 14:26:55,215 - ERROR - /root/.namecoin/namecoin.conf unreadable or missing, Namecoin support deactivated
2018-10-09 14:26:55,368 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "bitmessagemain.py", line 434, in <module>
    main()
  File "bitmessagemain.py", line 431, in main
    mainprogram.start()
  File "bitmessagemain.py", line 333, in start
    bitmessageqt.run()
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/__init__.py", line 4403, in run
    myapp = MyForm()
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/__init__.py", line 579, in __init__
    self.ui.setupUi(self)
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/bitmessageui.py", line 559, in setupUi
    self.blackwhitelist = Blacklist()
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/blacklist.py", line 17, in __init__
    widgets.load('blacklist.ui', self)
  File "/root/PROGRAMS/PyBitmessage-0.6.3.2/src/bitmessageqt/widgets.py", line 13, in load
    uic.loadUi(resource_path(resFile), widget)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 236, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py", line 50, in __init__
    UIParser.__init__(self, QtCore, QtGui, LoaderCreatorPolicy(package))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 183, in __init__
    self.factory = QObjectCreator(creatorPolicy)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 94, in __init__
    modinfo = plugin_locals["moduleInformation"]()
  File "<string>", line 52, in moduleInformation
  File "/usr/lib/python2.7/dist-packages/qgis/__init__.py", line 26, in <module>
    from qgis.PyQt import QtCore
  File "/usr/lib/python2.7/dist-packages/qgis/PyQt/QtCore.py", line 28, in <module>
    sip.setapi(api, 2)
ValueError: API 'QDate' has already been set to version 1`

**Comment by g1itch** [comment]
OK, I understood the problem is with some widget plugin from qgis.

**Comment by g1itch** [comment]
Is this also your post?
https://forums.kali.org/showthread.php?42270-How-to-get-PyBitMessage-running-on-latest-Kali

**Comment by bl4k1st** [comment]
yes

**Comment by g1itch** [comment]
Please try this patch:
```patch
diff --git a/src/depends.py b/src/depends.py
index 9a2e2158..481f4d4d 100755
--- a/src/depends.py
+++ b/src/depends.py
@@ -385,6 +385,11 @@ def check_pyqt():
     Here we are checking for PyQt4 with its version, as for it require
     PyQt 4.8 or later.
     """
+    try:
+        import sip
+        sip.setapi('QDate', 2)
+    except ImportError, ValueError:
+        pass
     QtCore = try_import(
         'PyQt4.QtCore', 'PyBitmessage requires PyQt 4.8 or later and Qt 4.7 or later.')
```

**Comment by bl4k1st** [comment]
`python bitmessagemain.py 
Loading existing config files from /root/.config/PyBitmessage/
2018-12-27 11:28:49,998 - WARNING - Using default logger configuration
make: Entering directory '/root/PROGRAMS/PyBitmessage/src/bitmsghash'
g++ -Wall -O3 -march=native -fPIC  -c bitmsghash.cpp
g++ bitmsghash.o -shared -fPIC -lcrypto -lpthread -o bitmsghash.so
make: Leaving directory '/root/PROGRAMS/PyBitmessage/src/bitmsghash'
2018-12-27 11:28:52,087 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "bitmessagemain.py", line 473, in <module>
    main()
  File "bitmessagemain.py", line 469, in main
    mainprogram.start()
  File "bitmessagemain.py", line 361, in start
    bitmessageqt.run()
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/__init__.py", line 4456, in run
    myapp = MyForm()
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/__init__.py", line 589, in __init__
    self.ui.setupUi(self)
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/bitmessageui.py", line 559, in setupUi
    self.blackwhitelist = Blacklist()
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/blacklist.py", line 17, in __init__
    widgets.load('blacklist.ui', self)
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/widgets.py", line 13, in load
    uic.loadUi(resource_path(resFile), widget)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 236, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py", line 50, in __init__
    UIParser.__init__(self, QtCore, QtGui, LoaderCreatorPolicy(package))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 183, in __init__
    self.factory = QObjectCreator(creatorPolicy)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 94, in __init__
    modinfo = plugin_locals["moduleInformation"]()
  File "<string>", line 52, in moduleInformation
  File "/usr/lib/python2.7/dist-packages/qgis/__init__.py", line 26, in <module>
    from qgis.PyQt import QtCore
  File "/usr/lib/python2.7/dist-packages/qgis/PyQt/QtCore.py", line 28, in <module>
    sip.setapi(api, 2)
ValueError: API 'QDateTime' has already been set to version 1`

**Comment by bl4k1st** [comment]
Adding this:
https://github.com/enthought/pyface/issues/286#issuecomment-335436808

results in 


> python bitmessagemain.py 
Loading existing config files from /root/.config/PyBitmessage/
2018-12-27 11:39:59,368 - WARNING - Using default logger configuration
2018-12-27 11:40:01,020 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "bitmessagemain.py", line 473, in <module>
    main()
  File "bitmessagemain.py", line 469, in main
    mainprogram.start()
  File "bitmessagemain.py", line 361, in start
    bitmessageqt.run()
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/__init__.py", line 4456, in run
    myapp = MyForm()
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/__init__.py", line 589, in __init__
    self.ui.setupUi(self)
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/bitmessageui.py", line 566, in setupUi
    self.networkstatus = NetworkStatus()
  File "/root/PROGRAMS/PyBitmessage/src/bitmessageqt/networkstatus.py", line 37, in __init__
    self.labelStartupTime.setText(_translate("networkstatus", "Since startup on %1").arg(
AttributeError: 'unicode' object has no attribute 'arg'

**Comment by g1itch** [comment]
No way. `bitmessageqt` currently uses `QString`. You can try `qt5-wip` branch or wait until I find a better workaround.

**Comment by bl4k1st** [comment]
Ok, I cloned qt5-wip, this is starting.
Thank you :)
