### ISSUE TITLE
openssl-1.1.1d: socket.error with Errno 0 while doing TLS handshake for inbound connection

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#1572]
Hello!

Recently I updated openssl to version 1.1.1d and now I see uncaptured exceptions for some inbound connections. I added the debug message:
```diff
diff --git a/src/network/tls.py b/src/network/tls.py
index d5c4e23a..edc48f98 100644
--- a/src/network/tls.py
+++ b/src/network/tls.py
@@ -203,6 +203,8 @@ class TLSDispatcher(AdvancedDispatcher):
             if err.errno in asyncore._DISCONNECTED:
                 self.handle_close()
             else:
+                logger.warning(
+                    'socket.error in asyncore thread:', exc_info=True)
                 raise
         else:
             if sys.version_info >= (2, 7, 9):
```
and now it looks like this:

```
2019-11-25 12:00:13,200 - WARNING - socket.error in asyncore thread:
Traceback (most recent call last):
  File "/home/glitch/test/PyBitmessage/pybitmessage/network/tls.py", line 189, in tls_handshake
    self.sslSocket.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
error: uncaptured python exception, closing channel <network.tcp.TCPConnection connected 127.0.0.1:34458 at 0x7fe9800cdb90> (<class 'socket.error'>:[Errno 0] Error [/home/glitch/test/PyBitmessage/pybitmessage/network/asyncore_pollchoose.py|readwrite|225] [/home/glitch/test/PyBitmessage/pybitmessage/network/asyncore_pollchoose.py|handle_read_event|804] [/home/glitch/test/PyBitmessage/pybitmessage/network/tcp.py|handle_read|255] [/home/glitch/test/PyBitmessage/pybitmessage/network/tls.py|handle_read|139] [/home/glitch/test/PyBitmessage/pybitmessage/network/tls.py|tls_handshake|189] [/usr/lib64/python2.7/ssl.py|do_handshake|828])
```

Now I have a working connection from PyBitmessage 0.6.1 with TLSv1.

**Comment by PeterSurda** [comment]
https://www.openssl.org/news/openssl-1.1.1-notes.html:

**Comment by PeterSurda** [comment]
I'm not sure 1.1.1 has been tested, only 1.1.0. Maybe the code doesn't handle it correctly.

**Comment by g1itch** [comment]
```sh
>> ssl._DEFAULT_CIPHERS
>> 'TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:DH+CHACHA20:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+HIGH:DH+HIGH:RSA+AESGCM:RSA+AES:RSA+HIGH:!aNULL:!eNULL:!MD5:!3DES'
```

**Comment by g1itch** [comment]
Some 0.6.3.2 have also connected with TLSv1.2

**Comment by g1itch** [comment]
Other 0.6.3.2 with openssl-1.1.1d connects without errors.

**Comment by g1itch** [comment]
Apparently this is a problem of incomplete update, maybe Gentoo specific. I stopped seeing it after full update and reboot. Still watching.
