### ISSUE TITLE
QT Plugin changes broke stuff

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1735]
Report came, haven't tested:

```
$ Documents/Software/PyBitmessage/src/bitmessagemain.py
2021-02-13 20:05:18,826 - WARNING - Using default logger configuration
2021-02-13 20:05:23,429 - WARNING - /home/*****/.namecoin/namecoin.conf unreadable or missing, Namecoin support deactivated
2021-02-13 20:05:23,435 - WARNING - There was a problem testing for a Namecoin daemon. Hiding the Fetch Namecoin ID button
2021-02-13 20:05:23,436 - CRITICAL - Unhandled exception
Traceback (most recent call last):
  File "Documents/Software/PyBitmessage/src/bitmessagemain.py", line 487, in <module>
  File "Documents/Software/PyBitmessage/src/bitmessagemain.py", line 483, in main
  File "Documents/Software/PyBitmessage/src/bitmessagemain.py", line 356, in start
  File "/home/*****/Documents/Software/PyBitmessage/src/bitmessageqt/__init__.py", line 4188, in run
    myapp = MyForm()
  File "/home/*****/Documents/Software/PyBitmessage/src/bitmessageqt/__init__.py", line 825, in __init__
    self.indicatorInit()
  File "/home/*****/Documents/Software/PyBitmessage/src/bitmessageqt/__init__.py", line 1435, in indicatorInit
    self.desktop = get_plugin('desktop')()
NameError: global name 'get_plugin' is not defined

```

**Comment by g1itch** [comment]
Oops! Now I'm thinking about adding a testing job without setuptools...
