### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by cande** [Bitmessage/PyBitmessage#233]
When launching from terminal (Runnning Ubutu 13.04) i get this:

Listening for incoming connections.
Traceback (most recent call last):
  File "bitmessagemain.py", line 4907, in <module>
    bitmessageqt.run()
  File "/home/christian/git/PyBitmessage/src/bitmessageqt/**init**.py", line 2933, in run
    myapp = MyForm()
  File "/home/christian/git/PyBitmessage/src/bitmessageqt/**init**.py", line 395, in **init**
    'bitmessagesettings', 'timeformat'), localtime(int(received))), 'utf-8'))
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte

There is also a thread about this on the forums:
https://bitmessage.org/forum/index.php/topic,1700.msg2939.html#msg2939

If messages.dat is removed, the issue disappear, so do all the messages, subscriptions and addresses to.

**Comment by kcraftcode** [comment]
@cande 
Thank you for inviting me to the project, but I would like you to elaborate on this.
