### ISSUE TITLE
daemon mode Error

### ISSUE THREAD

**Issue by themighty1** [Bitmessage/PyBitmessage#568]
I get this error while running with daemon = true

Traceback (most recent call last):
  File "/home/default/PyBitmessage-headless/src/bitmessagemain.py", line 1055, in <module>
    mainprogram.start()
  File "/home/default/PyBitmessage-headless/src/bitmessagemain.py", line 1027, in start
    bitmessageqt.run()
  File "/home/default/PyBitmessage-headless/src/bitmessageqt/__init__.py", line 3666, in run
    myapp = MyForm()
  File "/home/default/PyBitmessage-headless/src/bitmessageqt/__init__.py", line 535, in __init__
    self.loadSent()
  File "/home/default/PyBitmessage-headless/src/bitmessageqt/__init__.py", line 771, in loadSent
    if fromLabel == '':
UnboundLocalError: local variable 'fromLabel' referenced before assignment

**Comment by PeterSurda** [comment]
I've been running the daemon for a long time in a headless environment without problems and with no QT installed. @themighty1 , if you still experience this problem, reopen.
