### ISSUE TITLE
Get an error while running 2 Bitmessage clients in deamon mode on one machine

### ISSUE THREAD

**Issue by merlink01** [Bitmessage/PyBitmessage#583]
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/home/merlink/Workspace/Bitmessage/mainbug/PyBitmessage/src/class_singleListener.py", line 44, in run
    sock.bind((HOST, PORT))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Could this cause an error in the client, so that the connections to other peers get lost?

If yes, we should test this port before opening it.

**Comment by PeterSurda** [comment]
I'm not going to do anything about this for the time being. I tested this a couple of weeks ago for other reasons and while the listen thread crashed, Bitmessage continued to work.
