### ISSUE TITLE
PyBitmessage does not start 

### ISSUE THREAD

**Issue by nopenopenope** [Bitmessage/PyBitmessage#643]
Hi there, 

i read the Wiki and followed the instructions. I took a look at the dependencies, but there's everything needed. I also reinstalled the dependencies, but nothing worked.

I use Backtrack 5 R3 as OS. 

Heres the problem where I'm stuck:
nope@bt:~/PyBitmessage$ python src/bitmessagemain.py
Loading existing config files from /home/nope/.config/PyBitmessage/
Traceback (most recent call last):
  File "src/bitmessagemain.py", line 18, in <module>
    from api import MySimpleXMLRPCRequestHandler
  File "/home/nope/PyBitmessage/src/api.py", line 18, in <module>
    import shared
  File "/home/nope/PyBitmessage/src/shared.py", line 763, in <module>
    from debug import logger
  File "/home/nope/PyBitmessage/src/debug.py", line 71, in <module>
    configureLogging()
  File "/home/nope/PyBitmessage/src/debug.py", line 27, in configureLogging
    logging.config.dictConfig({
AttributeError: 'module' object has no attribute 'dictConfig'
nope@bt:~/PyBitmessage$ 

Im not sure whats the problem here. Can someone help me?

**Comment by PeterSurda** [comment]
@omyno, you are correct.

@nopenopenope please upgrade your python to 2.7.
