### ISSUE TITLE
debug log error

### ISSUE THREAD

**Issue by CNMan** [Bitmessage/PyBitmessage#890]
```python
2016-08-06 16:48:46,469 - CRITICAL - Critical error in a receiveDataThread: 
Traceback (most recent call last):
  File "src\class_receiveDataThread.py", line 190, in processData
  File "src\class_receiveDataThread.py", line 762, in recversion
  File "src\class_receiveDataThread.py", line 779, in sendverack
  File "src\class_receiveDataThread.py", line 273, in connectionFullyEstablished
  File "ssl.py", line 911, in wrap_socket
  File "ssl.py", line 522, in __init__
IOError: [Errno 2] No such file or directory
2016-08-06 16:50:18,071 - CRITICAL - Critical error in a receiveDataThread: 
Traceback (most recent call last):
  File "src\class_receiveDataThread.py", line 190, in processData
  File "src\class_receiveDataThread.py", line 762, in recversion
  File "src\class_receiveDataThread.py", line 779, in sendverack
  File "src\class_receiveDataThread.py", line 273, in connectionFullyEstablished
  File "ssl.py", line 911, in wrap_socket
  File "ssl.py", line 522, in __init__
IOError: [Errno 2] No such file or directory
2016-08-06 17:30:53,736 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "src\proofofwork.py", line 182, in <module>
  File "<string>", line 145, in __init__
  File "ctypes\__init__.py", line 365, in __init__
WindowsError: [Error 126] 
2016-08-06 17:30:53,742 - ERROR - C PoW test fail.
Traceback (most recent call last):
  File "src\proofofwork.py", line 192, in <module>
  File "<string>", line 124, in __init__
  File "ctypes\__init__.py", line 365, in __init__
WindowsError: [Error 126] 
```

**Comment by PeterSurda** [comment]
The first two could be missing ssl keys. They should be under the sslkeys directory, if you don't have them just create a new key (key.pem) and a self-signed certificate (cert.pem). Or it could be an old openssl library linked against python.

The third and fourth mean you don't have the C PoW module. You can build it with MinGW or MSVS, or you can download prebuilt binaries from https://github.com/mailchuck/PyBitmessage/releases. Or the message could just be a warning because mingw and msvs build different types of DLLs and PyBitmessage tests for both, so one may fail anyway.

**Comment by PeterSurda** [comment]
I thought you were running PyBitmessage from source, but maybe you're using the windows binary from the bitcoin.org site? That has some strange bugs, you can try a later development snapshot: https://mega.nz/#!ZcNlEDQJ!NcIFchGj6Ub4dFwDhkpzYRjuQXksIdtgAU1rt3dovYA

**Comment by CNMan** [comment]
yes,i am running the latest windows binary from bitcoin.org

**Comment by PeterSurda** [comment]
0.6.1 was released recently, the binaries were fixed, if it still didn't work, try them.
