### ISSUE TITLE
0.6.2 crash on windows

### ISSUE THREAD

**Issue by Rav3nPL** [Bitmessage/PyBitmessage#990]
After ~24h it is crashing, end of log:
`2017-04-04 10:24:30,405 - ERROR - An exception has occurred in the outgoingSynSender thread that was not caught by other exception types:
Traceback (most recent call last):
  File "class_outgoingSynSender.py", line 191, in run
  File "class_sendDataThread.py", line 33, in __init__
  File "threading.py", line 736, in start
error: can't start new thread
2017-04-04 10:25:11,390 - ERROR - An exception has occurred in the outgoingSynSender thread that was not caught by other exception types:
Traceback (most recent call last):
  File "class_outgoingSynSender.py", line 194, in run
  File "threading.py", line 736, in start
error: can't start new thread
2017-04-04 10:25:12,000 - ERROR - An exception has occurred in the outgoingSynSender thread that was not caught by other exception types:
Traceback (most recent call last):
  File "class_outgoingSynSender.py", line 191, in run
  File "class_sendDataThread.py", line 33, in __init__
  File "threading.py", line 736, in start
error: can't start new thread
2017-04-04 10:27:45,563 - ERROR - An exception has occurred in the outgoingSynSender thread that was not caught by other exception types:
Traceback (most recent call last):
  File "class_outgoingSynSender.py", line 191, in run
  File "class_sendDataThread.py", line 33, in __init__
  File "threading.py", line 736, in start
error: can't start new thread
2017-04-04 10:28:42,503 - ERROR - An exception has occurred in the outgoingSynSender thread that was not caught by other exception types:
Traceback (most recent call last):
  File "class_outgoingSynSender.py", line 191, in run
  File "class_sendDataThread.py", line 33, in __init__
  File "threading.py", line 736, in start
error: can't start new thread
2017-04-04 10:28:42,842 - ERROR - An exception has occurred in the outgoingSynSender thread that was not caught by other exception types:
Traceback (most recent call last):
  File "class_outgoingSynSender.py", line 191, in run
  File "class_sendDataThread.py", line 33, in __init__
  File "threading.py", line 736, in start
error: can't start new thread
2017-04-04 10:29:05,046 - CRITICAL - Major error occurred when trying to execute a SQL statement within the sqlThread. Please tell Atheros about this error message or post it in the forum! Error occurred while trying to execute statement: "SELECT objecttype, streamnumber, payload, expirestime, tag FROM inventory WHERE hash=?"  Here are the parameters; you might want to censor this data with asterisks (***) as it can contain private information: ('\x98\x089^\x93\xe5\x00\xd9\xa9\x96\x15}#lc\xbe.\x13\n"\x16\x94\x8e\xc8>p\x9f\xbb\x0c\x8a\x82\xbf',). Here is the actual error message thrown by the sqlThread: 
2017-04-04 10:29:05,046 - CRITICAL - This program shall now abruptly exit!
`

**Comment by Rav3nPL** [comment]
x32 version on x64 win10

**Comment by PeterSurda** [comment]
Thank you for providing a listening node. This is a known problem, there are several issues open about it. In the meantime, you can reduce maxtotalconnections in keys.dat (to say 20), or you can try the current v0.6 branch which has some fixes. I'll see if I can upload a snapshot binary for windows.

**Comment by PeterSurda** [comment]
Please try the latest development snapshot at htttps://bitmessage.org/download/snapshots/ (look for today's snapshot, i.e. 20170529) and let me know if it's better.

**Comment by Rav3nPL** [comment]
On win7 x64 no open port, after ~16h: RAM: ~115MB, CPU usage: one full core :/
It crashed on win10 x64 (external port open) after about 12-16hrs.
On both errors like that in debug.log:
```
2017-05-30 00:50:33,161 - ERROR - Received command inv before connection was fully established, ignoring
2017-05-30 06:59:01,226 - ERROR - 192.168.2.118:8444 error: 2, I'm connected to myself. Closing connection.
2017-05-30 07:00:01,259 - ERROR - 192.168.2.118:8444 error: 2, I'm connected to myself. Closing connection.
2017-05-30 07:01:11,384 - ERROR - 192.168.2.118:8444 error: 2, I'm connected to myself. Closing connection.
2017-05-30 07:01:29,217 - ERROR - Received command inv before connection was fully established, ignoring
2017-05-30 07:02:11,413 - ERROR - 192.168.2.118:8444 error: 2, I'm connected to myself. Closing connection.
2017-05-30 07:03:11,592 - ERROR - 192.168.2.118:8444 error: 2, I'm connected to myself. Closing connection.
```

**Comment by PeterSurda** [comment]
Thank you for the report. I did get other reports about crashes after several hours as well as excessive hogging of a single core. I hope to fix it within the next couple of days.

The errors you're posting are just minor issues. The "inv before fully established" is a new type of check that I introduced through tightening the protocol and can be triggered by older versions and maybe other bitmessage implementations as well. Tightening the protocol makes it more difficult to disrupt the connections.

The "connected to myself" is a minor bug in the the peer discovery, at the moment it doesn't realise when it receives its own discovery packet. Other than causing a bit more resource consumption it doesn't do anything bad.

**Comment by Rav3nPL** [comment]
Ok, on win10x64 (port open) it is working ~15h now. No CPU hogging, ~520MB RAM.
There is alot of traffic: 820MB send 2GB downloaded.
Also it says about 107 things to sync. How it can be not synced?
In log I can see many lines like:
```
2017-05-30 20:50:14,178 - WARNING - Peer(host='23.97.74.80', port=62514) asked for an object with a getdata which is not in either our memory inventory or our SQL inventory. We probably cleaned it out after advertising it but before they got around to asking for it.
2017-05-30 20:50:26,424 - WARNING - Peer(host='23.97.74.80', port=62514) asked for an object with a getdata which is not in either our memory inventory or our SQL inventory. We probably cleaned it out after advertising it but before they got around to asking for it.
2017-05-30 20:50:26,428 - WARNING - Peer(host='23.97.74.80', port=62514) asked for an object with a getdata which is not in either our memory inventory or our SQL inventory. We probably cleaned it out after advertising it but before they got around to asking for it.
2017-05-30 20:50:26,444 - WARNING - Peer(host='23.97.74.80', port=62514) asked for an object with a getdata which is not in either our memory inventory or our SQL inventory. We probably cleaned it out after advertising it but before they got around to asking for it.
2017-05-30 20:50:26,453 - WARNING - Peer(host='23.97.74.80', port=62514) asked for an object with a getdata which is not in either our memory inventory or our SQL inventory. We probably cleaned it out after advertising it but before they got around to asking for it.
2017-05-30 20:51:47,000 - ERROR - 85.114.135.102:55525 error: 2, Thank you for providing a listening node.
2017-05-30 21:05:05,230 - ERROR - 158.69.63.42:43570 error: 2, Thank you for providing a listening node.
2017-05-30 21:18:06,237 - ERROR - 85.114.135.102:34510 error: 2, Thank you for providing a listening node.
2017-05-30 21:33:06,025 - ERROR - 158.69.63.42:46514 error: 2, Thank you for providing a listening node.
2017-05-30 21:54:30,197 - ERROR - 85.114.135.102:44271 error: 2, Thank you for providing a listening node.
2017-05-30 22:05:56,631 - ERROR - 85.25.152.9:48857 error: 2, Thank you for providing a listening node.
2017-05-30 22:06:37,168 - ERROR - 158.69.63.42:52362 error: 2, Thank you for providing a listening node.
```
I hope it helps narrow down troubles.

**Comment by PeterSurda** [comment]
The syncing doesn't work correctly yet, it's a known problem, don't worry about it. The lines you posted are OK too, the 23.97.74.80 could be a bug or a lag, and the rest are the bootstrap nodes verifying that your node is accepting connections.

**Comment by Rav3nPL** [comment]
On win7x64 (no incoming conn) both dev versions (x32 and x64) hogging one cpu core.
Nothing new in log.
x32 mem usage after ~8hrs <70MB

**Comment by PeterSurda** [comment]
I think the original problems with crash had to do with running low on disk space or something similar, the other problems with connectivity/CPU should be fixed by now, I haven't seen similar behaviour recently.
